[tool.poetry]
name = "oxford-genai-llmops-project"
version = "0.1.0"
description = "A microservice for Retrieval-Augmented Generation over scientific abstracts"
authors = ["Geoffrey <jameslambert062@gmail.com>"]

# Tell Poetry where to find your package
packages = [
  { include = "oxford_genai_llmops_project", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
