name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install --no-cache-dir poetry

      - name: Install dependencies
        run: poetry install --no-root --no-interaction

      - name: Run tests
        run: poetry run pytest -q
